package com.dorcaapps.android.ktorclient.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF206c2f)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa6f5a7)
val md_theme_light_onPrimaryContainer = Color(0xFF002106)
val md_theme_light_secondary = Color(0xFF526350)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd5e8d0)
val md_theme_light_onSecondaryContainer = Color(0xFF0f1f10)
val md_theme_light_tertiary = Color(0xFF006493)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc7e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e30)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfdf7)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfdf7)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdee5d9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1eb)
val md_theme_light_inverseSurface = Color(0xFF2e312d)

val md_theme_dark_primary = Color(0xFF8ad88d)
val md_theme_dark_onPrimary = Color(0xFF00390d)
val md_theme_dark_primaryContainer = Color(0xFF005319)
val md_theme_dark_onPrimaryContainer = Color(0xFFa6f5a7)
val md_theme_dark_secondary = Color(0xFFb8ccb4)
val md_theme_dark_onSecondary = Color(0xFF243424)
val md_theme_dark_secondaryContainer = Color(0xFF3a4b39)
val md_theme_dark_onSecondaryContainer = Color(0xFFd5e8d0)
val md_theme_dark_tertiary = Color(0xFF89ceff)
val md_theme_dark_onTertiary = Color(0xFF00344f)
val md_theme_dark_tertiaryContainer = Color(0xFF004b70)
val md_theme_dark_onTertiaryContainer = Color(0xFFc7e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9be)
val md_theme_dark_outline = Color(0xFF8b9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dd)

val seed = Color(0xFF3d8345)
val error = Color(0xFFba1b1b)